apiVersion: v1
kind: Service
metadata:
  name: log-service
spec:
  ports:
    - port: 4000
  selector:
    app: log-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
        - name: log-service
          image: log-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/logs"
